### ISSUE TITLE
CurrentLanguage returns wrong language

### ISSUE THREAD

**Issue by LyraPony** [Facepunch/Facepunch.Steamworks#234] opened 2019-01-31 21:15 UTC
`string lang = Client.Instance.CurrentLanguage;`

lang always = english, even with other languages. What can be wrong?

**Comment by kscarlett** [comment] 2019-02-02 23:08
Seems like a duplicate of #214 

I've recently run into the same issue myself. I might try to track down what's causing this.

**Closed** 2019-04-30 15:38 UTC
